version: '3.9'

services:
  rancher:
    image: rancher/rancher:latest
    privileged: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - rancher_home:/var/lib/rancher
volumes:
  rancher_home: